const INPUT_TYPES = {
  TEXT: 'TEXT',
  EMAIL: 'EMAIL',
  PASSWORD: 'PASSWORD',
  CONFIRM_PASSWORD: 'CONFIRM_PASSWORD',
  NUMBER: 'NUMBER',
  PHONE: 'PHONE',
  OPTIONAL: 'OPTIONAL',
};

export {INPUT_TYPES};
